実行するとエラーがでるが、写経は完了したので一旦コミット。
エラー内容:
$ node twithash/web.js
(node) sys is deprecated. Use util instead.
/Users/macoril/Develop/node.js_sample_project/twithash/web.js:3
      app = express.createServer(),
                    ^

TypeError: express.createServer is not a function
    at Object.<anonymous> (/Users/macoril/Develop/node.js_sample_project/twithash/web.js:3:21)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)
    at node.js:999:3