express関連の記述を変えて、最新のexpressで動くように修正
cf.
http://stackoverflow.com/questions/13499010/nodejs-express-launching-my-app-express-createserver-is-deprecated
"app.configure() has been removed. Use process.env.NODE_ENV or app.get('env') to detect the environment and configure the app accordingly"
Q.What's the solution here to support the equivalent of the configure() function ? - gnB
A.just call app.use directly - Rafael
http://stackoverflow.com/questions/29694647/app-configurefunction-typeerror-undefined-is-not-a-function

エラー内容:
/Users/macoril/Develop/node.js_sample_project/node_modules/socket.io/lib/index.js:201
    throw new Error(msg);
    ^

Error: You are trying to attach socket.io to an express request handler function. Please pass a http.Server instance.
    at Server.listen.Server.attach (/Users/macoril/Develop/node.js_sample_project/node_modules/socket.io/lib/index.js:201:11)
    at new Server (/Users/macoril/Develop/node.js_sample_project/node_modules/socket.io/lib/index.js:50:17)
    at Function.Server (/Users/macoril/Develop/node.js_sample_project/node_modules/socket.io/lib/index.js:38:41)
    at Object.<anonymous> (/Users/macoril/Develop/node.js_sample_project/twithash/web.js:16:19)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)